// Organized permission features for better UI display
export const PERMISSION_FEATURES = {
  Dashboard: ['FEATURE_DASHBOARD_VIEW', 'FEATURE_ANALYTICS_VIEW'],
  Orders: [
    'FEATURE_ORDERS_VIEW',
    'FEATURE_ORDERS_CREATE',
    'FEATURE_ORDERS_EDIT',
    'FEATURE_ORDERS_DELETE',
  ],
  Trips: [
    'FEATURE_TRIPS_VIEW',
    'FEATURE_TRIPS_CREATE',
    'FEATURE_TRIPS_EDIT',
    'FEATURE_TRIPS_DELETE',
    'FEATURE_TRIPS_ODOMETER_VIEW',
    'FEATURE_TRIPS_HANDLE_VOUCHER',
  ],
  Drivers: [
    'FEATURE_DRIVERS_VIEW',
    'FEATURE_DRIVERS_CREATE',
    'FEATURE_DRIVERS_EDIT',
    'FEATURE_DRIVERS_DELETE',
    'FEATURE_DRIVERS_DOCUMENTS_VIEW',
  ],
  Trucks: [
    'FEATURE_TRUCKS_VIEW',
    'FEATURE_TRUCKS_CREATE',
    'FEATURE_TRUCKS_VIEW_DETAILS',
    'FEATURE_TRUCKS_EDIT',
    'FEATURE_TRUCKS_DELETE',
    'FEATURE_TRUCKS_TOOLKIT_DETAILS',
    'FEATURE_TRUCKS_MAINTENANCE_HISTORY',
    'FEATURE_TRUCKS_AUDIT_HISTORY',
  ],
  Clients: [
    'FEATURE_CLIENTS_VIEW',
    'FEATURE_CLIENTS_CREATE',
    'FEATURE_CLIENTS_EDIT',
    'FEATURE_CLIENTS_DELETE',
  ],
  Receivers: [
    'FEATURE_RECEIVERS_VIEW',
    'FEATURE_RECEIVERS_CREATE',
    'FEATURE_RECEIVERS_EDIT',
    'FEATURE_RECEIVERS_DELETE',
  ],
  Centers: [
    'FEATURE_CENTERS_VIEW',
    'FEATURE_CENTERS_CREATE',
    'FEATURE_CENTERS_EDIT',
    'FEATURE_CENTERS_DELETE',
  ],
  Attendance: ['FEATURE_ATTENDANCE_VIEW'],
  Requests: ['FEATURE_REQUESTS_VIEW', 'FEATURE_REQUESTS_APPROVE', 'FEATURE_REQUESTS_REJECT'],
  Wallets: [
    'FEATURE_WALLETS_VIEW',
    'FEATURE_WALLETS_CREATE',
    'FEATURE_WALLETS_EDIT',
    'FEATURE_WALLETS_DELETE',
    'FEATURE_WALLETS_TRANSACTIONS_VIEW',
  ],
  TATs: ['FEATURE_TATS_VIEW', 'FEATURE_TATS_CREATE', 'FEATURE_TATS_EDIT', 'FEATURE_TATS_DELETE'],
  Ratecard: ['FEATURE_RATECARD_VIEW'],
  Admin: ['FEATURE_ADMIN_PANEL', 'FEATURE_PERMISSIONS_MANAGE', 'FEATURE_SYSTEM_SETTINGS'],
} as const;

// Flatten features for backward compatibility
export const FEATURE_IDS = Object.values(PERMISSION_FEATURES).flat();

export type FeatureId = (typeof FEATURE_IDS)[number];

// Available roles in the system
export const AVAILABLE_ROLES = ['admin', 'manager', 'accountant', 'driver'] as const;
export type Role = (typeof AVAILABLE_ROLES)[number];

// Default permissions by role
export const DEFAULT_ROLE_PERMISSIONS: Record<string, FeatureId[]> = {
  admin: FEATURE_IDS.slice(), // All permissions
  manager: [
    'FEATURE_DASHBOARD_VIEW',
    'FEATURE_ANALYTICS_VIEW',
    'FEATURE_ORDERS_VIEW',
    'FEATURE_ORDERS_CREATE',
    'FEATURE_ORDERS_EDIT',
    'FEATURE_ORDERS_DELETE',
    'FEATURE_DRIVERS_VIEW',
    'FEATURE_DRIVERS_CREATE',
    'FEATURE_DRIVERS_EDIT',
    'FEATURE_DRIVERS_DELETE',
    'FEATURE_DRIVERS_DOCUMENTS_VIEW',
    'FEATURE_TRIPS_VIEW',
    'FEATURE_TRIPS_CREATE',
    'FEATURE_TRIPS_EDIT',
    'FEATURE_TRIPS_DELETE',
    'FEATURE_TRIPS_ODOMETER_VIEW',
    'FEATURE_TRIPS_HANDLE_VOUCHER',
    'FEATURE_TRUCKS_VIEW',
    'FEATURE_CLIENTS_VIEW',
    'FEATURE_RECEIVERS_VIEW',
    'FEATURE_CENTERS_VIEW',
    'FEATURE_ATTENDANCE_VIEW',
    'FEATURE_REQUESTS_VIEW',
    'FEATURE_REQUESTS_APPROVE',
    'FEATURE_REQUESTS_REJECT',
    'FEATURE_RATECARD_VIEW',
    'FEATURE_WALLETS_VIEW',
    'FEATURE_TATS_VIEW',
  ],
  accountant: ['FEATURE_DASHBOARD_VIEW', 'FEATURE_ANALYTICS_VIEW'],
  driver: ['FEATURE_DASHBOARD_VIEW', 'FEATURE_ANALYTICS_VIEW'],
};
