export const FEATURE_IDS = [
  // Dashboard features
  'FEATURE_DASHBOARD_VIEW',
  'FEATURE_ANALYTICS_VIEW',
  
  // Orders features
  'FEATURE_ORDERS_VIEW',
  'FEATURE_ORDERS_CREATE',
  'FEATURE_ORDERS_EDIT',
  'FEATURE_ORDERS_DELETE',
  
  // Drivers features
  'FEATURE_DRIVERS_VIEW',
  'FEATURE_DRIVERS_CREATE',
  'FEATURE_DRIVERS_EDIT',
  'FEATURE_DRIVERS_DELETE',
  'FEATURE_DRIVERS_DOCUMENTS_VIEW',
  
  // Trips features
  'FEATURE_TRIPS_VIEW',
  'FEATURE_TRIPS_CREATE',
  'FEATURE_TRIPS_EDIT',
  'FEATURE_TRIPS_DELETE',
  
  // Trucks features
  'FEATURE_TRUCKS_VIEW',
  'FEATURE_TRUCKS_CREATE',
  'FEATURE_TRUCKS_EDIT',
  'FEATURE_TRUCKS_DELETE',
  
  // Clients features
  'FEATURE_CLIENTS_VIEW',
  'FEATURE_CLIENTS_CREATE',
  'FEATURE_CLIENTS_EDIT',
  'FEATURE_CLIENTS_DELETE',
  
  // Receivers features
  'FEATURE_RECEIVERS_VIEW',
  'FEATURE_RECEIVERS_CREATE',
  'FEATURE_RECEIVERS_EDIT',
  'FEATURE_RECEIVERS_DELETE',
  
  // Centers features
  'FEATURE_CENTERS_VIEW',
  'FEATURE_CENTERS_CREATE',
  'FEATURE_CENTERS_EDIT',
  'FEATURE_CENTERS_DELETE',
  
  // Attendance features
  'FEATURE_ATTENDANCE_VIEW',
  'FEATURE_ATTENDANCE_MANAGE',
  
  // Requests features
  'FEATURE_REQUESTS_VIEW',
  'FEATURE_REQUESTS_APPROVE',
  'FEATURE_REQUESTS_REJECT',
  
  // Wallets features
  'FEATURE_WALLETS_VIEW',
  'FEATURE_WALLETS_CREATE',
  'FEATURE_WALLETS_EDIT',
  'FEATURE_WALLETS_DELETE',
  'FEATURE_WALLETS_TRANSACTIONS_VIEW',
  
  // TATs features
  'FEATURE_TATS_VIEW',
  'FEATURE_TATS_CREATE',
  'FEATURE_TATS_EDIT',
  'FEATURE_TATS_DELETE',
  
  // Teams/Users features
  'FEATURE_TEAMS_VIEW',
  'FEATURE_TEAMS_CREATE',
  'FEATURE_TEAMS_EDIT',
  'FEATURE_TEAMS_DELETE',
  
  // Ratecard features
  'FEATURE_RATECARD_VIEW',
  'FEATURE_RATECARD_EDIT',
  
  // Reports and Analytics
  'FEATURE_REPORTS_VIEW',
  'FEATURE_REPORTS_EXPORT',
  
  // Admin features
  'FEATURE_ADMIN_PANEL',
  'FEATURE_PERMISSIONS_MANAGE',
  'FEATURE_SYSTEM_SETTINGS',
  
  // Financial features
  'FEATURE_INVOICING_VIEW',
  'FEATURE_INVOICING_CREATE',
  'FEATURE_INVOICING_EDIT',
  'FEATURE_PAYMENTS_VIEW',
  'FEATURE_PAYMENTS_PROCESS',
] as const;

export type FeatureId = typeof FEATURE_IDS[number];

// Default permissions by role
export const DEFAULT_ROLE_PERMISSIONS: Record<string, FeatureId[]> = {
  admin: FEATURE_IDS.slice(), // All permissions
  manager: [
    'FEATURE_DASHBOARD_VIEW',
    'FEATURE_ANALYTICS_VIEW',
    'FEATURE_ORDERS_VIEW',
    'FEATURE_ORDERS_CREATE',
    'FEATURE_ORDERS_EDIT',
    'FEATURE_DRIVERS_VIEW',
    'FEATURE_DRIVERS_CREATE',
    'FEATURE_DRIVERS_EDIT',
    'FEATURE_DRIVERS_DOCUMENTS_VIEW',
    'FEATURE_TRIPS_VIEW',
    'FEATURE_TRIPS_CREATE',
    'FEATURE_TRIPS_EDIT',
    'FEATURE_TRUCKS_VIEW',
    'FEATURE_CLIENTS_VIEW',
    'FEATURE_RECEIVERS_VIEW',
    'FEATURE_CENTERS_VIEW',
    'FEATURE_ATTENDANCE_VIEW',
    'FEATURE_ATTENDANCE_MANAGE',
    'FEATURE_REQUESTS_VIEW',
    'FEATURE_REQUESTS_APPROVE',
    'FEATURE_REQUESTS_REJECT',
    'FEATURE_WALLETS_VIEW',
    'FEATURE_WALLETS_TRANSACTIONS_VIEW',
    'FEATURE_TATS_VIEW',
    'FEATURE_REPORTS_VIEW',
  ],
  accountant: [
    'FEATURE_DASHBOARD_VIEW',
    'FEATURE_ORDERS_VIEW',
    'FEATURE_INVOICING_VIEW',
    'FEATURE_INVOICING_CREATE',
    'FEATURE_INVOICING_EDIT',
    'FEATURE_PAYMENTS_VIEW',
    'FEATURE_PAYMENTS_PROCESS',
    'FEATURE_WALLETS_VIEW',
    'FEATURE_WALLETS_TRANSACTIONS_VIEW',
    'FEATURE_REPORTS_VIEW',
    'FEATURE_REPORTS_EXPORT',
  ],
  driver: [
    'FEATURE_DASHBOARD_VIEW',
    'FEATURE_ORDERS_VIEW',
    'FEATURE_TRIPS_VIEW',
    'FEATURE_ATTENDANCE_VIEW',
    'FEATURE_REQUESTS_VIEW',
  ],
};
